#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only

import argparse
import hashlib
import io
import pathlib
import zipfile


FIXED_ZIP_TIME = (2026, 1, 1, 0, 0, 0)
EXPECTED_PLUGIN_FILES = 3
EXPECTED_ARTWORK_FILES = 28


def is_release_file(path: pathlib.Path) -> bool:
    name = path.name
    return not (
        name == ".DS_Store"
        or name.startswith("._")
        or name.endswith("~")
        or path.suffix.lower() == ".psd"
    )


def collect_files(root: pathlib.Path, directory_name: str):
    source = root / directory_name
    if not source.is_dir():
        raise SystemExit(f"Missing resource directory: {source}")

    files = []
    for path in sorted(source.rglob("*")):
        if path.is_file() and is_release_file(path):
            files.append((path, pathlib.PurePosixPath(directory_name) / path.relative_to(source).as_posix()))
    return files


def build_zip(plugin_files, artwork_files):
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path, arcname in plugin_files + artwork_files:
            info = zipfile.ZipInfo(str(arcname), FIXED_ZIP_TIME)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, path.read_bytes())
    return output.getvalue()


def format_bytes(data: bytes):
    lines = []
    for offset in range(0, len(data), 512):
        chunk = data[offset : offset + 512]
        escaped = "".join(f"\\{byte:03o}" for byte in chunk)
        lines.append(f'    "{escaped}"')
    return "\n".join(lines)


def write_if_changed(path: pathlib.Path, text: str):
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    return True


def main():
    parser = argparse.ArgumentParser(description="Generate standalone embedded runtime resources.")
    parser.add_argument("--root", type=pathlib.Path, required=True, help="Repository root")
    parser.add_argument("--output", type=pathlib.Path, required=True, help="Output C++ source path")
    args = parser.parse_args()

    root = args.root.resolve()
    plugin_files = collect_files(root / "Resources", "plugins")
    artwork_files = collect_files(root, "artwork")

    if len(plugin_files) != EXPECTED_PLUGIN_FILES:
        raise SystemExit(f"Expected {EXPECTED_PLUGIN_FILES} plugin files, found {len(plugin_files)}")
    if len(artwork_files) != EXPECTED_ARTWORK_FILES:
        raise SystemExit(f"Expected {EXPECTED_ARTWORK_FILES} artwork files, found {len(artwork_files)}")

    zip_data = build_zip(plugin_files, artwork_files)
    digest = hashlib.sha256(zip_data).hexdigest()

    source = f"""// SPDX-License-Identifier: AGPL-3.0-only
// Generated by tools/generate-standalone-runtime-resources.py. Do not edit by hand.

#include "EmbeddedStandaloneRuntimeResources.h"

namespace
{{
const char standaloneRuntimeResourcesZip[] =
{format_bytes(zip_data)}
;
constexpr std::size_t standaloneRuntimeResourcesZipSize = {len(zip_data)};

struct RuntimeResourcePayloadRegistration
{{
    RuntimeResourcePayloadRegistration()
    {{
        ves::standalone_resources::registerPayload ({{
            reinterpret_cast<const unsigned char*> (standaloneRuntimeResourcesZip),
            standaloneRuntimeResourcesZipSize,
            "{digest}"
        }});
    }}
}};

RuntimeResourcePayloadRegistration runtimeResourcePayloadRegistration;
}}
"""

    changed = write_if_changed(args.output, source)
    status = "updated" if changed else "unchanged"
    print(f"{status}: {args.output}")
    print(f"payload_sha256={digest}")
    print(f"payload_bytes={len(zip_data)}")
    print(f"plugin_files={len(plugin_files)}")
    print(f"artwork_files={len(artwork_files)}")


if __name__ == "__main__":
    main()
